name: Production Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened,reopened, synchronize]

jobs:
  migrate:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: ./.github/workflows/migrate.yml
    with:
      environment: production
