name: Production Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened,reopened, synchronize]

jobs:
  migrate:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    environment: production
    env:
      ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
    uses: ./.github/workflows/migrate.yml
